
name: Unit Tests


on:
  fork:
  pull_request:
    types: [opened, edited, closed]
  push:
  release:
    types: [published, created, edited, released]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Linux Tests
        uses: actions/checkout@v2
      - name: Ubuntu - Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: |
          echo "Linux-Tests: Preloading package dependencies ..."
          python3 -m pip install anyio mmh3 mypy packaging pip pytest pytest-env pytest-cov requests types-toml types-requests furl
          echo "Linux-Tests: Running tests ..."
          mkdir -p ~/.justuse-python/
          echo "debug = true" > ~/.justuse-python/config.toml
          python3 -m pip install --force-reinstall --upgrade -r requirements.txt
          python3 -m pip install -r requirements.txt furl
          IFS=$'\n'; set -- $( find -name "*.py" | cut -c 3- | sed -r -e 's~^src/~~; s~\.py~~; \~^\.|/\.~d; s~/~.~g; s~\.__init__$~~; s~^~--cov=~; ' ; ); python3 -m pytest --cov-branch --cov-report term-missing --cov-report html:coverage/ --cov-report annotate:coverage/annotated --cov-report xml:coverage/cov.xml "$@"
      - name: coverage.py badge
        uses: tj-actions/coverage-badge-py@v1.6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 20fb71ba-3e2b-46db-b86d-e1666d56665b
          CODECOV_TOKEN: 20fb71ba-3e2b-46db-b86d-e1666d56665b
          fail_ci_if_error: false # optional (default = false)
          files: ./.coverage,./coverage/cov.xml # optional
          flags: unittests # optional
          name: codecov-justuse # optional
          verbose: true # optional (default = false)
          github-token: ${{ secrets.PAT_TOKEN }}

